### ISSUE TITLE
React Native App crashes without any error log on android. 

### ISSUE THREAD

**Issue by ZeikhTech** [boostlingo/react-native-boostlingo-sdk#4]
The app we have crashes when we try to do a video call using the boostlingo react native sdk. It crashes without an error or log. It works on iOS, app doesn't crash there. It only crashes on android when we try to do video call.

React Native version: 0.61.5.
Android emulator: Pixel 3A , API level 32, arm-64 version.

**Comment by dkornev** [comment]
Hey @ZeikhTech 
Can you reproduce this issue using the example application?
Since I can't reproduce this issue with the example application, please provide the device's native logs so I will be able to start the investigation.

**Comment by ZeikhTech** [comment]
> Hey @ZeikhTech Can you reproduce this issue using the example application? Since I can't reproduce this issue with the example application, please provide the device's native logs so I will be able to start the investigation.

The thing is, it is working in the example app. But it crashes in our app. We have the same code as the code in the example app.

**Comment by ZeikhTech** [comment]
> Hey @ZeikhTech Can you reproduce this issue using the example application? Since I can't reproduce this issue with the example application, please provide the device's native logs so I will be able to start the investigation.

04-07 21:50:21.774  4914  4914 E AndroidRuntime: FATAL EXCEPTION: main
04-07 21:50:21.774  4914  4914 E AndroidRuntime: Process: com.volatiaapp, PID: 4914
04-07 21:50:21.774  4914  4914 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/twilio/video/VideoRenderer$Listener;
04-07 21:50:21.774  4914  4914 E AndroidRuntime: 	at com.reactnativeboostlingosdk.BLVideoViewManager.createViewInstance(BLVideoViewManager.kt:23)
04-07 21:50:21.774  4914  4914 E AndroidRuntime: 	at com.reactnativeboostlingosdk.BLVideoViewManager.createViewInstance(BLVideoViewManager.kt:14)
04-07 21:50:21.774  4914  4914 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java:139)
04-07 21:50:21.774  4914  4914 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:82)
04-07 21:50:21.774  4914  4914 E AndroidRuntime: 	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:269)
04-07 21:50:21.774  4914  4914 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:179)
04-07 21:50:21.774  4914  4914 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:773)
04-07 21:50:21.774  4914  4914 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:888)
04-07 21:50:21.774  4914  4914 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue.access$2200(UIViewOperationQueue.java:42)
04-07 21:50:21.774  4914  4914 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:948)
04-07 21:50:21.774  4914  4914 E AndroidRuntime: 	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:28)
04-07 21:50:21.774  4914  4914 E AndroidRuntime: 	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:174)
04-07 21:50:21.774  4914  4914 E AndroidRuntime: 	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)
04-07 21:50:21.774  4914  4914 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1035)
04-07 21:50:21.774  4914  4914 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
04-07 21:50:21.774  4914  4914 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:775)
04-07 21:50:21.774  4914  4914 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
04-07 21:50:21.774  4914  4914 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
04-07 21:50:21.774  4914  4914 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-07 21:50:21.774  4914  4914 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
04-07 21:50:21.774  4914  4914 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
04-07 21:50:21.774  4914  4914 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7842)
04-07 21:50:21.774  4914  4914 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-07 21:50:21.774  4914  4914 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
04-07 21:50:21.774  4914  4914 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
04-07 21:50:21.774  4914  4914 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.twilio.video.VideoRenderer$Listener" on path: DexPathList[[zip file "/data/app/~~G9vMk4LysJ-FrzukKh2HkA==/com.volatiaapp-kjGXrnygf2PVNgj6q4tIdA==/base.apk"],nativeLibraryDirectories=[/data/app/~~G9vMk4LysJ-FrzukKh2HkA==/com.volatiaapp-kjGXrnygf2PVNgj6q4tIdA==/lib/arm64, /data/app/~~G9vMk4LysJ-FrzukKh2HkA==/com.volatiaapp-kjGXrnygf2PVNgj6q4tIdA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
04-07 21:50:21.774  4914  4914 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
04-07 21:50:21.774  4914  4914 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
04-07 21:50:21.774  4914  4914 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
04-07 21:50:21.774  4914  4914 E AndroidRuntime: 	... 25 more
04-07 21:50:21.834  4914  4914 I Process : Sending signal. PID: 4914 SIG: 9

Maybe this will help

**Comment by dkornev** [comment]
@ZeikhTech 
This error might happen due to the code shrinking (https://developer.android.com/studio/build/shrink-code)

Please make sure that you are adding correct rules into your _proguard-rules.pro_ file.
https://github.com/boostlingo/react-native-boostlingo-sdk/blob/master/example/android/app/proguard-rules.pro

**Comment by ZeikhTech** [comment]
> @ZeikhTech This error might happen due to the code shrinking (https://developer.android.com/studio/build/shrink-code)
> 
> Please make sure that you are adding correct rules into your _proguard-rules.pro_ file. https://github.com/boostlingo/react-native-boostlingo-sdk/blob/master/example/android/app/proguard-rules.pro

We did this, it still crashes with same log. Here is the postguard file:
<img width="1222" alt="Screenshot 2022-04-08 at 11 32 32 AM" src="https://user-images.githubusercontent.com/59015625/162378152-bf063494-6623-4c03-a2f0-ab44d849ca75.png">

**Comment by Samaustin222** [comment]
@dkornev

**Comment by dkornev** [comment]
It still looks like a code shrinking problem since one of the Twilio SDK classes (com.twilio.video.VideoRenderer$Listener) is missing from the result apk.

Are you sure that you are adding all the dependencies needed for the SDK properly (https://github.com/boostlingo/react-native-boostlingo-sdk/blob/master/android/build.gradle)?

The Android SDK's code hasn't changed for almost 2 years. I really think that you need to track your local changes first.

**Comment by dkornev** [comment]
Did you ever have this issue before?
I assume that you had your android app working fine for a long time, right?

**Comment by ZeikhTech** [comment]
Yes but we faced this issue recently and since we work on react native side we are not familiar with the native sides. Can you please provide a documentation on how to use the library with react native or you can just tell us how to configure it for the android that would be really helpful. Settings/configuration for the gradle/kotlin/java files etc.

**Comment by ZeikhTech** [comment]
> Yes but we faced this issue recently and since we work on react native side we are not familiar with the native sides. Can you please provide a documentation on how to use the library with react native or you can just tell us how to configure it for the android that would be really helpful. Settings/configuration for the gradle/kotlin/java files etc.


@dkornev any help

**Comment by ZeikhTech** [comment]
Hello, @dkornev 

We have checked out local changes, there is nothing wrong in there, and since there is no documentations for Android native settings, can you please guide us to resolve this error or provide us documentation please? 

Lots of our clients are complaining about it, since they cannot use Video feature, Audio works fine, since Boostlingo Video keeps on crashing even with the gradle settings being updated like you said. 

Would appreciate the help, and looking forward to hear from you soon. 

Thanks and Kind Regards,

**Comment by dkornev** [comment]
Еhe latest version of Twilio (voice and video) SDK requires Java.VERSION_11 and the new version of Gradle (tool and plugin). To fix the issue I had to downgrade to the previous version of Java and Gradle an use specific earlier versions of the Twilio SDKs .
